kind: ConfigMap
apiVersion: v1
metadata:
  name: configurations-ms-legacy-enrutador
data:
  ms.configuration.rest.producer.pathAcumulacion: 
  ms.configuration.rest.producer.pathReclamacion: 
  ms.configuration.rest.producer.pathValidacion: 



