---
- name: Checking SSH connectivity to Kubernetes Master Instance
  hosts: localhost
  become: yes
  tasks:
    - name: Wait for AWS Instance SSH to come up
      wait_for:
        host: "{{ groups['aws_k8s_master_host'][0] }}"
        port: 22
        state: started

- name: Deploying Docker on AWS Instance
  hosts: aws_k8s_master_host
  roles:
    - role: docker

- name: Deploying Kubernetes Master Role on AWS Instance
  hosts: aws_k8s_master_host
  roles:
    - role: gantsign.minikube
...